services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financial_statement_app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/financial_statement_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    volumes:
      - ./src/main/resources/static:/app/static
      - ./data/files:/app/data/files
#    depends_on:
#      - db
#
#  db:
#    image: postgres:latest
#    container_name: db
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: financial_statement_db
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#volumes:
#  postgres_data: