server:
  port: 8080
spring:
  application:
    name: FinancialStatement
  freemarker:
    expose-session-attributes: true

  # ------------- DataBases
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qwe
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

  output:
    ansi:
      enabled: always


logging:
  level:
    root: info
    org:
      springframework:
        security: debug
  file:
    path: logs