<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="/footer/footer.css">
</head>
<body>
<footer class="bg-success text-white text-center py-4 mt-auto">
    <div class="container">
        <p>&copy; 2024 Financial Statement ♡</p>
        <p>
            <a href="/admin/users" class="text-white">Пользователи</a> |
            <a href="/tasks" class="text-white">Таски</a> |
            <a href="/companies" class="text-white">Компании</a>
        </p>
    </div>
</footer>
</body>
</html>