--liquibase formatted sql
--changeset Kamilla:036
insert into roles_authorities(role_id, authority_id)
values ((select id from roles where role = 'ROLE_ADMIN'),(select id from authorities where authority = 'CREATE_USER')),
       ((select id from roles where role = 'ROLE_ADMIN'),(select id from authorities where authority = 'DELETE_USER')),
       ((select id from roles where role = 'ROLE_ADMIN'),(select id from authorities where authority = 'EDIT_USER')),
       ((select id from roles where role = 'ROLE_ADMIN'),(select id from authorities where authority = 'VIEW_USER')),
       ((select id from roles where role = 'ROLE_ADMIN'),(select id from authorities where authority = 'CREATE_COMPANY')),
       ((select id from roles where role = 'ROLE_ADMIN'),(select id from authorities where authority = 'DELETE_COMPANY')),
       ((select id from roles where role = 'ROLE_ADMIN'),(select id from authorities where authority = 'EDIT_COMPANY')),
       ((select id from roles where role = 'ROLE_ADMIN'),(select id from authorities where authority = 'VIEW_COMPANY')),
       ((select id from roles where role = 'ROLE_ADMIN'),(select id from authorities where authority = 'CREATE_ROLE')),
       ((select id from roles where role = 'ROLE_ACCOUNTANT'),(select id from authorities where authority = 'CREATE_TASK')),
       ((select id from roles where role = 'ROLE_ACCOUNTANT'),(select id from authorities where authority = 'DELETE_TASK')),
       ((select id from roles where role = 'ROLE_ACCOUNTANT'),(select id from authorities where authority = 'EDIT_TASK')),
       ((select id from roles where role = 'ROLE_ACCOUNTANT'),(select id from authorities where authority = 'VIEW_TASK')),
       ((select id from roles where role = 'ROLE_ACCOUNTANT'),(select id from authorities where authority = 'CREATE_COMPANY')),
       ((select id from roles where role = 'ROLE_ACCOUNTANT'),(select id from authorities where authority = 'DELETE_COMPANY')),
       ((select id from roles where role = 'ROLE_ACCOUNTANT'),(select id from authorities where authority = 'EDIT_COMPANY')),
       ((select id from roles where role = 'ROLE_ACCOUNTANT'),(select id from authorities where authority = 'VIEW_COMPANY')),
       ((select id from roles where role = 'ROLE_MANAGER'),(select id from authorities where authority = 'VIEW_TASK')),
       ((select id from roles where role = 'ROLE_MANAGER'),(select id from authorities where authority = 'VIEW_USER')),
       ((select id from roles where role = 'ROLE_MANAGER'),(select id from authorities where authority = 'VIEW_COMPANY')),
       ((select id from roles where role = 'ROLE_JUNIOR_ADMIN'),(select id from authorities where authority = 'CREATE_USER')),
       ((select id from roles where role = 'ROLE_JUNIOR_ADMIN'),(select id from authorities where authority = 'DELETE_USER')),
       ((select id from roles where role = 'ROLE_JUNIOR_ADMIN'),(select id from authorities where authority = 'EDIT_USER')),
       ((select id from roles where role = 'ROLE_JUNIOR_ADMIN'),(select id from authorities where authority = 'VIEW_USER')),
       ((select id from roles where role = 'ROLE_JUNIOR_ADMIN'),(select id from authorities where authority = 'CREATE_COMPANY')),
       ((select id from roles where role = 'ROLE_JUNIOR_ADMIN'),(select id from authorities where authority = 'DELETE_COMPANY')),
       ((select id from roles where role = 'ROLE_JUNIOR_ADMIN'),(select id from authorities where authority = 'EDIT_COMPANY')),
       ((select id from roles where role = 'ROLE_JUNIOR_ADMIN'),(select id from authorities where authority = 'VIEW_COMPANY'));