name: Financial Statement Deployment

on:
  workflow_dispatch
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: daniyaraa/financial_statement_image:latest

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: financial_statement.jar
          path: ./target/financial_statement*.jar
          retention-days: 1

  publish:
    needs: build
    name: Publish Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          name: financial_statement.jar

      - name: Login
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Publish
        run: |
          docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker push ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}
          
  deploy:

    needs: publish
    name: Deploy Docker Image

    runs-on: ubuntu-latest

    steps:
      - name: Connect to SSH and pull Docker Image
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to SSH and pull Docker Image
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          mkdir -p ${{ secrets.WORK_DIR }}
          cd ${{ secrets.WORK_DIR }}
          docker compose pull
          docker compose up -d
          exit
          EOF
